name: Deploy LEMP Stack with WordPress

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository files
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH key for EC2 access
      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Install necessary tools
      - name: Install necessary tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl unzip rsync

      # Step 4: Add EC2 instance to known_hosts to avoid SSH host verification
      - name: Add EC2 instance to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # Step 5: Copy repository files, including deploy.sh, to EC2 instance
      - name: Copy files to EC2 instance
        run: |
          echo "Copying repository files to the EC2 instance..."
          rsync -avz --exclude '.git' ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/

      # Step 6: Run the deploy.sh script on EC2
      - name: Run deployment script
        run: |
          echo "Running deploy.sh script on EC2..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'bash /home/${{ secrets.REMOTE_USER }}/deploy.sh'

      # Step 7: Clean up
      - name: Clean up
        run: |
          echo "Deployment completed successfully!"
