name: Deploy LEMP Stack with WordPress

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository files
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH key for EC2 access
      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Install necessary tools
      - name: Install necessary tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl unzip rsync

      # Step 4: Copy repository files to EC2 instance
      - name: Copy files to EC2 instance
        run: |
          echo "Copying repository files to the EC2 instance..."
          rsync -avz --exclude '.git' ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/

      # Step 5: Deploy LEMP stack and WordPress using deploy.sh script
      - name: Run deployment script
        run: |
          echo "Running deploy.sh script on EC2..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'bash -s' < ./deploy.sh

      # Step 6: Clean up
      - name: Clean up
        run: |
          echo "Deployment completed successfully!"
