name: Deploy Static Website to Nginx

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH keys for accessing the Droplet
    - name: Set up SSH keys
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa your_droplet_ip >> ~/.ssh/known_hosts

    # Step 3: Download and deploy static website to the server
    - name: Deploy Static Website to Droplet
      run: |
        echo "Deploying static website to Droplet..."

        # Define the Droplet details
        DROPLET_USER="root"
        DROPLET_IP="64.227.133.104"
        WEB_DIR="/var/www/html"
        ZIP_URL="https://www.free-css.com/assets/files/free-css-templates/download/page285/cial.zip"
        
        # SSH into the Droplet and deploy
        ssh $DROPLET_USER@$DROPLET_IP << EOF
          # Step 4: Install unzip if it's not already installed
          sudo apt update
          sudo apt install -y unzip

          # Step 5: Download and unzip the static website files
          cd /tmp
          wget $ZIP_URL -O cial.zip
          unzip cial.zip -d cial
          sudo cp -r /tmp/cial/* $WEB_DIR/

          # Step 6: Set correct permissions
          sudo chown -R www-data:www-data $WEB_DIR
          sudo chmod -R 755 $WEB_DIR

          # Step 7: Configure Nginx for the static website
          echo "Configuring Nginx..."
          sudo bash -c 'cat > /etc/nginx/sites-available/static-site << EOL
          server {
              listen 80;
              server_name your_droplet_ip_or_domain;

              root /var/www/html;
              index index.html;

              location / {
                  try_files \$uri \$uri/ =404;
              }
          }
          EOL'

          # Enable the Nginx configuration
          sudo ln -s /etc/nginx/sites-available/static-site /etc/nginx/sites-enabled/

          # Test Nginx configuration and restart Nginx
          sudo nginx -t
          sudo systemctl restart nginx

          echo "Deployment complete!"
        EOF
